name: 'PR CI'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  flutter_test:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
      - name: Flutter Test
        run: |
          flutter pub get
          flutter test
